apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-170505213
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-170505213
    app.kubernetes.io/part-of: test-app-170505213
  name: java-quarkus-170505213
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-170505213
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-170505213
    spec:
      containers:
      - image: quay.io/hacdev/ziqrhsa0-tenant/test-app-170505213/java-quarkus-170505213@sha256:4e3e72a1b9213d6f37cf45189b326deb1949d50f9fe55a6fbf486b2fd6fc7e43
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
